=== julenmg/lab7/xml/galderak.dtd
<?xml version="1.0"?>
<!ELEMENT assessmentItems(assessmentItem+)>
<!ATTLIST assessmentItem
complexity CDATA #REQUIRE
subject CDATA #REQUIRE
>
<!ELEMENT assessmentItem(itemBody,correctResponse)>
<!ELEMENT itemBody(p)>
<!ELEMENT correctResponse>
<!ELEMENT p (#PCDATA)>
<!ELEMENT value (#PCDATA)>

=== julenmg/lab7/xml/galderak.xml
<?xml version="1.0"?>
<!DOCTYPE assessmentItems SYSTEM "galderak.dtd">
<?xml-stylesheet href="galderak.xsl" type="text/xsl"?>
<assessmentItems>
	<assessmentItem complexity="3" subject="Mikologia">
		<itemBody> 
			<p>Amanita muskaria zer da?</p>
		</itemBody>
		<correctResponse>
			<value>Perretxikoa</value>
		</correctResponse>
	</assessmentItem>
	<assessmentItem complexity="5" subject="Mikologia">
		<itemBody>
			<p>Amanita hilkorrena da:</p>
		</itemBody>
		<correctResponse>
			<value>Phalloides</value>
		</correctResponse>
	</assessmentItem>
<assessmentItem complexity="3" subject="Mikologia"><itemBody><p>zer da amanita muskaria?</p></itemBody><correctResponse><value>perretxikoak</value></correctResponse></assessmentItem></assessmentItems>
